=== GFan99/Anno2/src/application/DataFormatter_neu.xsd
<?xml version="1.0" encoding="utf-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.bioforscher.de/fosil/DataFormatter"
	xmlns:ns="http://www.bioforscher.de/fosil/DataFormatter"
	elementFormDefault="qualified" attributeFormDefault="unqualified">

	<element name="element" type="ns:DataEntity"></element>
	<complexType name="DataEntity">
		<sequence>
			<element name="TextEntity" type="ns:TextEntity"></element>	
		</sequence>
	</complexType>

	<complexType name="TextEntity">
		<sequence>
			<!-- Source to raw text -->
			<element name="source" type="string"></element>

			<!-- Unique id (name) for text -->
			<element name="textID" type="string"></element>

			<!-- Raw text -->
			<element name="text" type="string"></element>

			<!-- Annotation items -->
			<element name="annotations" type="ns:AnnotationItem"></element>

			<!-- Rater ID -->
			<element name="raterID" type="string"></element>
		</sequence>
	</complexType>

	<!-- To decide items should be defined here -->
	<complexType name="AnnotationItem">
		<sequence>
			<!-- classification label -->
			<element name="label" type="ns:Label"></element>

		</sequence>
	</complexType>

	<!-- one or multiple answers possible -->
	<complexType name="Label">
		<choice>
			<!-- only one answer possible(rating) -->
			<element name="class_rating" type="integer"></element>
			
			<!-- more answers possible or answer is a term(terms) -->
			<element name="class_terms" type="string"></element>
		</choice>
		
		<!-- name-attribute for Label -->
		<attribute name="name" type="string"></attribute>
	</complexType>
</schema>

=== GFan99/Anno2/src/application/DataFormatter_neu.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns:element xmlns:ns="http://www.bioforscher.de/fosil/DataFormatter" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.bioforscher.de/fosil/DataFormatter DataFormatter_neu.xsd ">
  <ns:TextEntity>
    <ns:source>ns:source</ns:source>
    <ns:textID>ns:textID</ns:textID>
    <ns:text>ns:text</ns:text>
    <ns:annotations>
      <ns:label name="">
        <ns:class_rating>0</ns:class_rating>
      </ns:label>
    </ns:annotations>
    <ns:raterID>ns:raterID</ns:raterID>
  </ns:TextEntity>
</ns:element>
